import SinglePost from '@/components/Posts/SinglePost';
import { getAllPosts } from '@/lib/notionAPI';
import { Inter } from 'next/font/google';
import Head from 'next/head';

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();

  return {
    props: {
      allPosts,
    },
    revalidate: 60 * 60 * 6,
  };
};

const inter = Inter({ subsets: ['latin'] });

export default function Home({ allPosts }) {
  console.log(allPosts);
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">Notion Blog🚀</h1>
        {allPosts.map((post, index) => (
          <div className="mx-4" key={index}>
            <SinglePost title={post.title} description={post.description} date={post.date} tags={post.tags} slug={post.slug} />
          </div>
        ))}
      </main>
    </div>
  );
}
